name: Mantener Hub Turaco Vivo

on:
  schedule:
    # Se ejecuta TODOS los días a las 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Permite ejecución manual para probar

jobs:
  ping_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Simular Visita de Navegador
        run: |
          # Realiza una petición completa simulando Chrome en Windows
          curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" https://appsmarketplaces.streamlit.app/
